default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  url: postgres://fernanda:121296@db:5432/chat_api_development

development:
  <<: *default
  database: chat_api_development

test:
  <<: *default
  database: chat_api_test
  url: <%= ENV['TEST_DATABASE_URL'] %>


production:
  <<: *default
  database: chat_api_production
  username: chat_api
  password: <%= ENV["CHAT_API_DATABASE_PASSWORD"] %>
